### ISSUE TITLE
Apply new UI design

### ISSUE THREAD

**Issue by Bullrich** [paritytech/polkadot-testnet-faucet#266]
Using the new [Figma file](https://www.figma.com/file/o7VivvuEtLbMTqTMgBWkeP/Polkadot-Faucet?node-id=1-2), we need to apply this new design to the current web faucet

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/issues/270
- [x] Apply new background
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/issues/268
```

Small nitpick. The `feedback` button should be replaced for a `Report an issue` button, and the `Questions` buttons should point to the forum instead of a mail address.
