### ISSUE TITLE
[EngAut]: Faucet improvements (Q3 epic)

### ISSUE THREAD

**Issue by mutantcornholio** [paritytech/polkadot-testnet-faucet#313]
Goals here:
* Adopt faucet from DevOps team, we should be responsible for all the maintenance, as well as code
* Refactor codebase
* Improve resilience, replicate faucet so failed deployments wouldn't break it
* Improve docs
* Improve UX
* Sort out backlog, including dependency updates

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/issues/298
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/issues/299
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/issues/262
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/issues/104
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/pull/309
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/pull/300
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/pull/305
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/pull/296
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/issues/328
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/issues/327
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/issues/315
```
